# Generated by Django 4.2.30 on 2026-08-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchedemail',
            name='in_reply_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fetchedemail',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
    ]
