# Generated by Django 4.2.30 on 2026-08-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
